name: Terraform GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan --out tfplan.binary

    - name: Terraform Show
      run: terraform show -json tfplan.binary > tfplan.json

    - name: Install Conftest
      run: |
        curl -L https://github.com/open-policy-agent/conftest/releases/download/v0.23.0/conftest_0.23.0_Linux_x86_64.tar.gz | tar xz
        sudo mv conftest /usr/local/bin

    - name: Conftest
      run: conftest test tfplan.json